title: Daytime ejector bed
hero_image: images/banner.png
description: Create a LEGO minifigure bed that tips up at sunrise and lies back at sunset.
version: 4
listed: false
copyedit: false
last_tested: "2022-02-01"
steps:
  - title: Introduction
  - title: Control the motor
  - title: Delay the spin
    completion: engaged
  - title: Build a bed
  - title: Track your daylight 
  - title: Set the alarm
    completion: internal
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion: external
  - title: Upgrade your project
  - title: What next?
