title: Daytime ejector bed
hero_image: images/banner.png
description: daytime-ejector-bed description
version: 4
listed: false
copyedit: false
last_tested: "2022-02-01"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
